version: "3.3"
volumes:
  data:
    driver: local
  filestore:
    driver: local
services:
  db_hedera:
    container_name: db_hedera
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: root
      PSQL_USERNAME: root
      PGDATA: /data/postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/data/postgres
  api-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["yarn", "api-service:prod"]
    ports:
      - "3001:3001"
    depends_on:
      - db_hedera
    environment:
      API_SERVICE_PORT: 3001
      DB_HOST: db_hedera
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: "123"
      DB_NAME: db_hedera
  custodian-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["yarn", "custodian-service:prod"]
    ports:
      - "3002:3002"
    environment:
      CUSTODIAN_SERVICE_PORT: 3002
      POLICY_ID: 67760bd322fd747bdc5f3b62
