version: "3.3"
volumes:
  data:
    driver: local
  filestore:
    driver: local
services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: root
      PSQL_USERNAME: root
      # POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/data/postgres
  national:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "root"
      RUN_MODULE: national-api
      rootEmail: <ROOT EMAIL>
      cfAdminEmail: <CLIMATE FUND ADMIN EMAIL>
      exComAdminEmail: <EXCECUTIVE COMMITTEE ADMIN EMAIL>
      Ministery: ""
      Department: ""
      systemCountryCode: "LK"
      systemCountryName: "Sri Lanka"
      systemContinentName: "Sri Lanka"
      name: "Antactic Region"
      climateFundName: "Sri Lanka Climate Fund"
      exComName: "Executive Committee"
      logoBase64: "sss"
      IS_EMAIL_DISABLED: "true"
      DISABLE_LOW_PRIORITY_EMAIL: "true"
      EMAILPREFIX: ""
      LOCATION_SERVICE: FILE
      ASYNC_OPERATIONS_TYPE: Database
      HOST: "http://localhost:3030"
      DOMAIN_MAP: "true"
      EXPIRES_IN: "7200"
      REFRESH_TOKEN_EXPIRES_IN: "12h"
      BACKEND_HOST: "http://192.168.1.16:3000"
      CONTACT_EMAIL: countryx@email.com
      MINISTER_NAME_AND_DESIGNATION: "\nHonorable Minister X\nMinister\nMinistry of Environment, Forestry & Tourism"
    volumes:
      - filestore:/app/backend/services/public
      - ./users.csv:/app/backend/services/users.csv
      - ./organisations.csv:/app/backend/services/organisations.csv
  stats:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    ports:
      - "3100:3100"
    depends_on:
      - db
      - national
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "root"
      RUN_PORT: 3100
      RUN_MODULE: analytics-api
      DOMAIN_MAP: "true"
  replicator:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    depends_on:
      - db
      - national
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "root"
      # ,data-importer
      RUN_MODULE: replicator,async-operations-handler
      LOCATION_SERVICE: OPENSTREET
      SMTP_ENDPOINT: email-smtp.us-east-1.amazonaws.com
      SMTP_USERNAME: AKIAUMXKTXDJEQ555F4J
      SMTP_PASSWORD: ""
      IS_EMAIL_DISABLED: "true"
      DISABLE_LOW_PRIORITY_EMAIL: "true"
      EMAILPREFIX: ""
      ASYNC_OPERATIONS_TYPE: Database
      ITMO_API_KEY: ""
      ITMO_EMAIL: ""
      ITMO_PASSWORD: ""
      MRV_ENDPOINT: "http://192.168.123.20:9000"
      SYNC_ENABLE: false
      MRV_API_TOKEN: ""
      BACKEND_HOST: "http://192.168.1.16:3000"
    volumes:
      - filestore:/app/backend/services/public
  # async-operations-handler:
  #   build:
  #     context: .
  #     dockerfile: ./backend/services/Dockerfile
  #   depends_on:
  #     - db
  #     - national
  #   environment:
  #     DB_HOST: db
  #     DB_USER: root
  #     DB_PASSWORD: "<ANY PASSOWORD>"
  #     RUN_MODULE: async-operations-handler
  #     SMTP_ENDPOINT: email-smtp.us-east-1.amazonaws.com
  #     SMTP_PASSWORD: "<ANY PASSOWORD>"
  #     ASYNC_OPERATIONS_TYPE: Database
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        PORT: 3030
        REACT_APP_BACKEND: http://localhost:3000
        REACT_APP_STAT_URL: http://localhost:3100
        REACT_APP_COUNTRY_NAME: "CountryX"
        REACT_APP_GOVERNMENT_MINISTRY: "Ministry Of Environment"
        REACT_APP_COUNTRY_FLAG_URL: "https://carbon-common-dev.s3.amazonaws.com/flag.png"
        REACT_APP_COUNTRY_CODE: "NG"
        REACT_APP_MAP_TYPE: "None"
        REACT_APP_MAPBOXGL_ACCESS_TOKEN: ""
    ports:
      - "3030:3030"
    depends_on:
      - db
      - national
