export const ministryGovDepMapping: Record<string, string[]> = {
    Agriculture: [
        'Cocoa Research Institute',
        'National Agricultural Extension, Research and Liaison Services',
        'National Veterinary Research Institute',
        'Agricultural Insurance Corporation',
        'National Root Crops Research Institute',
        'Agricultural Research Council',
        'Institute for Oceanography and Marine Research',
        'Institute for Oil Palm Research',
        'Agricultural Quarantine Service',
        'National Horticultural Research Institute',
    ],
    Aviation: [
        'Federal Airports Authority',
        'Airspace Management Agency',
        'Civil Aviation Authority',
        'Safety Investigation Bureau',
        'Meteorological Agency',
        'College of Aviation Technology',
    ],
    Communications: [
        'National Information Technology Development Agency',
        'Satellite Limited',
        'Broadcasting Commission',
        'Commission',
        'Postal Service',
        'National Frequency Management Council',
        'Television Authority',
        'Galaxy Backbone',
    ],
    Economy: [
        'Asset Management Corporation',
        'Social Security Administration',
        'Budget Office of the Federation',
        'Bureau of Public Enterprises',
        'Bureau of Public Procurement',
        'Central Bank',
        'Corporate Affairs Commission',
        'Debt Management Office',
        'Inland Revenue Service',
        'Mortgage Bank',
        'Fiscal Responsibility Commission',
        'Infrastructure Concession Regulatory Commission',
        'National Bureau of Statistics',
        'National Council on Privatisation',
        'National Insurance Commission',
        'National Pension Commission',
        'National Planning Commission',
        'National Sugar Development Council',
        'Niger Delta Development Commission',
        'Customs Service',
        'Deposit Insurance Corporation',
        'Investment Promotion Commission',
        'Export - Import Bank',
        'Export Promotion Council',
        'Oil and Gas Free Zones Authority',
        'Export Processing Zones Authority',
        'Revenue Mobilisation Allocation and Fiscal Commission',
        'Securities and Exchange Commission',
        'Standards Organisation',
        'Small and Medium Enterprise Development Agency',
    ],
    Education: [
        'National Board for Arabic And Islamic Studies',
        'Joint Admissions and Matriculation Board',
        'National Examination Council',
        'National Open University',
        'National Teachers Institute',
        'National Universities Commission',
        'Tertiary Education Trust Fund',
        'Teachers Registration Council',
        'National Business and Technical Examinations Board',
        'Universal Basic Education Commission',
        'West African Examination Council',
        'National Commission for Colleges of Education',
        'National Library',
    ],
    Energy: [
        'Midstream and Downstream Petroleum Regulatory Authority',
        'Upstream Petroleum Regulatory Commission',
        'Electricity Management Services Limited',
        'Energy Commission',
        'National Power Training Institute',
        'Electricity Regulatory Commission',
        'Content Monitoring and Development Board',
        'National Petroleum Corporation',
        'Nuclear Regulatory Authority',
        'Petroleum Product Pricing Regulatory Agency',
        'Power Holding Company (defunct)',
        'Rural Electrification Agency',
        'Transmission Company',
    ],
    Environment: [
        'Environmental Protection Agency (defunct)',
        'Forestry Research Institute',
        'National Biosafety Management Agency',
        'National Environmental Standards and Regulations Enforcement Agency',
        'National Oil Spill Detection and Response Agency',
        'Environmental Health Officers Registration Council',
    ],
    Health: [
        'National Health Insurance Scheme',
        'Institute for Pharmaceutical Research and Development',
        'Agency for the Control of AIDS',
        'Agency for Food and Drug Administration and Control',
        'Primary Health Care Development Agency',
        'Institute of Medical Research',
        'Centre for Disease Control',
        'Drug Law Enforcement Agency',
    ],
    Intelligence: [
        'Defence Intelligence Agency',
        'State Security Service',
        'National Intelligence Agency',
        'Financial Intelligence Unit',
    ],
    Judiciary: [
        'National Judicial Council',
        'Federal Judicial Service Commission',
        'National Judicial Institute',
    ],
    Maritime: [
        'Maritime Administration and Safety Agency',
        'Ports Authority',
        "Shippers' Council",
    ],
    Media: [
        'Broadcasting Organisation',
        'News Agency',
        'Press Council',
        'Television Authority',
    ],
    ScienceAndTechnology: [
        'Agency For Science and Engineering Infrastructure',
        'Biotechnology Development Agency',
        'Centre for Remote Sensing',
        'Science and Technology Complex',
        'Office for Technology Acquisition and Promotion',
        'Space Research and Development Agency',
        'Nuclear Regulatory Authority',
        'Raw Materials Research and Development Council',
        'Communications Satellite Ltd',
        'Centre for Technology Management',
    ],
    WaterResources: [
        'Hydrological Services Agency',
        'Integrated Water Resources Commission',
        'Water Resources Institute',
        'River Basin Development Authorities',
    ],
    Other: [
        'Centre for Black and African Arts and Civilization',
        'Automotive Design and Development Council',
        'Code of Conduct Bureau',
        'Computer Professionals Registration Council',
        'Consumer Protection Council',
        'Economic and Financial Crimes Commission',
        'Federal Character Commission',
        'Federal Housing Authority',
        'Corrupt Practices and Other Related Offences Commission',
        'Independent National Electoral Commission',
        'Industrial Training Fund',
        'Legal Aid Council',
        'Agency for the Prohibition of Trafficking in Persons',
        'National Boundary Commission',
        'National Council of Arts and Culture',
        'Economic Reconstruction Fund',
        'Emergency Management Agency',
        'Hajj Commission',
        'Human Rights Commission',
        'Identity Management Commission',
        'Institute for Hospitality Tourism',
        'Lottery Regulatory Commission',
        'Orientation Agency',
        'Population Commission',
        'Poverty Eradication Programme (defunct)',
        'Salaries, Incomes and Wages Commission',
        'Sports Commission',
        'Extractive Industries Transparency Initiative',
        'Immigration Service',
        'Building and Road Research Institute',
        'Institute of Building',
        'Christian Pilgrim Commission',
        'Copyright Commission',
        'Tourism Development Corporation',
        'Public Complaints Commission',
        'Surveyors Council',
        'National Lottery Trust Fund',
    ],
};
