export enum ProjectProposalStage {
  SUBMITTED_INF = 'SUBMITTED_INF',
  APPROVED_INF = 'APPROVED_INF',
  REJECTED_INF = 'REJECTED_INF',
  ACCEPTED_INF = 'ACCEPTED_INF',
  VALIDATION_PENDING = 'VALIDATION_PENDING',
  VALIDATED = 'VALIDATED',
  AUTHORISED = 'AUTHORISED',
}

export enum CreditType {
  TRACK_1 = 'TRACK_1',
  TRACK_2 = 'TRACK_2',
}
