export enum ProjectProposalStage {
  SUBMITTED_INF = "SUBMITTED_INF",
  APPROVED_INF = "APPROVED_INF",
  REJECTED_INF = "REJECTED_INF",
  ACCEPTED_PROPOSAL = "ACCEPTED_PROPOSAL",
  REJECTED_PROPOSAL = "REJECTED_PROPOSAL",
  SUBMITTED_CMA = "SUBMITTED_CMA",
  REJECTED_CMA = "REJECTED_CMA",
  VALIDATION_PENDING = "VALIDATION_PENDING",
  AUTHORISED = "AUTHORISED",
}
