export enum VerificationRequestStatusEnum {
  MONITORING_REPORT_UPLOADED = "MONITORING_REPORT_UPLOADED",
  MONITORING_REPORT_VERIFIED = "MONITORING_REPORT_VERIFIED",
  MONITORING_REPORT_REJECTED = "MONITORING_REPORT_REJECTED",
  VERIFICATION_REPORT_UPLOADED = "VERIFICATION_REPORT_UPLOADED",
  VERIFICATION_REPORT_VERIFIED = "VERIFICATION_REPORT_VERIFIED",
  VERIFICATION_REPORT_REJECTED = "VERIFICATION_REPORT_REJECTED",
}
